import { ThemeProvider } from "@/components/ThemeProvide";
import type { Metadata } from "next";
import "./globals.css";
import ModifiedToaster from "@/components/ModifiedToaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <ThemeProvider attribute="class" enableSystem disableTransitionOnChange>
          {children}
          <ModifiedToaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
