import VerifyTokenForm from "@/components/VerifyTokenForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Verify Your Acc",
  description: "Generated by create next app",
};
const Page = () => {
  return (
    <main>
      <VerifyTokenForm />
    </main>
  );
};

export default Page;
