import RegisterForm from "@/components/RegisterForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register Page",
  description: "Generated by create next app",
};
const Page = () => {
  return (
    <main>
      <RegisterForm />
    </main>
  );
};

export default Page;
